version: '3.2'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: front-end
    container_name: frontend-demo
    ports:
    - "4200:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- ./frontend:/app
    #- /app/node_modules

    restart: always
    
  # workaround to Docker issue https://github.com/moby/moby/issues/38564
  #  volumes:
  #  - ./front-end/e2e:/app/e2e
  #  - ./front-end/src:/app/src
  workflow:
    build:
      dockerfile: Dockerfile
      context: workflowui
    container_name: workflow-demo
    ports:
    - "4208:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- ./frontend:/app
    #- /app/node_modules

    restart: always