version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: back-end
    container_name: backend-demo
    ports:
    - "9091:51773"
    - "9092:52773"
    volumes:
    - ./back-end:/app

  #frontend:
  #  build:
  #    dockerfile: Dockerfile
  #    context: front-end
  #  container_name: frontend-demo
  #  ports:
  #  - "4200:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- ./frontend:/app
    #- /app/node_modules
    
    # workaround to Docker issue https://github.com/moby/moby/issues/38564
  #  volumes:
  #  - ./front-end/e2e:/app/e2e
  #  - ./front-end/src:/app/src
